#pragma once

//#define RETRO_TAPPING
//#define PERMISSIVE_HOLD
//#define HOLD_ON_OTHER_KEY_PRESS


#define TAPPING_TERM 200
#define PERMISSIVE_HOLD
//#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
//#define NO_ACTION_ONESHOT
#define RETRO_TAPPING_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY
